name: First github action

on:
  push:
    branches:
      - master
      - develop
      - feature/boundary_sectors
  pull_request:
    branches:
      - master
      - develop
      - feature/boundary_sectors
  workflow_dispatch:

jobs:
  dispaset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: this is dispaset
        run: echo "This is Dispa-SET"
        shell: bash
