name: Testing

on:
  push:
    branches:
      - master
      - develop
      - feature/boundary_sectors
  pull_request:
    branches:
      - master
      - develop
      - feature/boundary_sectors
  workflow_dispatch:

jobs:
  dispaset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: this is dispaset
        run: echo "Torture Dispa-SET"
        shell: bash
  miniconda:
    name: Miniconda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    env:
      GAMS: 24.9
      GAMS_URL: https://d37drm4t2jghv5.cloudfront.net/distributions/24.9.2/linux/linux_x64_64_sfx.exe
      CC_TEST_REPORTER_ID: 4de43419e620692eff68510258e9428a6da4e5dca96ef9deb7744566ad3a7386

    steps:
      - uses: actions/checkout@v4
      - name: Install GAMS
        run: |
          wget -N $GAMS_URL -O gams.zip
          unzip -qu gams.zip -d $HOME
          ln -s $HOME/gams${GAMS}_linux_x64_64_sfx $HOME/gams
          export GAMSPATH="$HOME/gams"
          export PATH="$GAMSPATH:$PATH"
          cd $HOME/gams
          gamsinst -a
          cd -

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: dispaset
          environment-file: environment.yml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          pip install -e .
          conda info
          conda list
          conda config --show-sources
          conda config --show

#      - name: Lint
#        shell: bash -l {0}
#        run: |
#            conda install flake8
#            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        shell: bash -l {0}
        run: |
            conda install pytest
            pytest